export const CourseCategory = [
  "Programming Basics",
  "Web Development",
  "JavaScript",
  "Java Programming",
  "C++",
  "Data Science",
  "Full-Stack Development",
  "Machine Learning",
  "Frontend Development",
  "iOS App Development",
  "Android App Development",
  "Game Development",
  "Database Management",
  "Blockchain Development",
  "DevOps",
  "Cybersecurity",
  "Cloud Computing",
  "Data Structures and Algorithms",
  "Data Analysis",
  "Artificial Intelligence",
  "Mobile App Development",
];
